DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NAME" VARCHAR(100) NOT NULL
);

CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NAME" VARCHAR(150) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    category_id INT,
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT NOT NULL CHECK (quantity > 0),
    subtotal DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE OR REPLACE FUNCTION validate_order_item_subtotal()
RETURNS TRIGGER AS $$
DECLARE
    product_price DECIMAL(10,2);
BEGIN
    SELECT price INTO product_price
    FROM products
    WHERE id = NEW.product_id;

    IF ROUND(NEW.subtotal::numeric, 2) <> ROUND((product_price * NEW.quantity)::numeric, 2) THEN
        RAISE EXCEPTION 'Error: El subtotal no coincide con Precio * Cantidad';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER before_insert_order_items
BEFORE INSERT ON order_items
FOR EACH ROW
EXECUTE FUNCTION validate_order_item_subtotal();

CREATE TRIGGER before_update_order_items
BEFORE UPDATE ON order_items
FOR EACH ROW
EXECUTE FUNCTION validate_order_item_subtotal();

INSERT INTO categories ("NAME") VALUES
('Electrónica'),
('Hogar'),
('Deportes'),
('Libros'),
('Oficina');

INSERT INTO products ("NAME", price, category_id) VALUES
('Laptop', 10.00, 1),
('Silla', 20.00, 2),
('Balón', 30.00, 3),
('Novela', 40.00, 4),
('Escritorio', 50.00, 5);

INSERT INTO users (username, email) VALUES
('user1', 'user1@example.com'),
('user2', 'user2@example.com'),
('user3', 'user3@example.com'),
('user4', 'user4@example.com'),
('user5', 'user5@example.com');

INSERT INTO orders (user_id) VALUES
(1),
(2),
(3),
(4),
(5);

INSERT INTO order_items (order_id, product_id, quantity, subtotal) VALUES
(1, 1, 1, 10.00),
(2, 2, 2, 40.00),
(3, 3, 3, 90.00),
(4, 4, 4, 160.00),
(5, 5, 5, 250.00);

SELECT
    c.id,
    c."NAME" AS category,
    COALESCE(SUM(oi.subtotal), 0) AS total_sold
FROM categories c
JOIN products p ON p.category_id = c.id
JOIN order_items oi ON oi.product_id = p.id
GROUP BY c.id, c."NAME"
ORDER BY c.id;

DO $$
BEGIN
    BEGIN
        INSERT INTO order_items (order_id, product_id, quantity, subtotal)
        VALUES (1, 1, 2, 15.00);
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE '%', SQLERRM;
    END;
END $$;