DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE categories (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"NAME" VARCHAR(100) NOT NULL
);

CREATE TABLE products (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"NAME" VARCHAR(150) NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	category_id INT,
	FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE users (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE orders (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE order_items (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_id INT,
	product_id INT,
	quantity INT NOT NULL CHECK (quantity > 0),
	subtotal DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (order_id) REFERENCES orders(id),
	FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE OR REPLACE FUNCTION validate_order_item_subtotal()
RETURNS TRIGGER AS $$
DECLARE
	product_price DECIMAL(10,2);
BEGIN
	SELECT price INTO product_price
	FROM products
	WHERE id = NEW.product_id;

	IF ROUND(NEW.subtotal::numeric, 2) <> ROUND((product_price * NEW.quantity)::numeric, 2) THEN
		RAISE EXCEPTION 'Error: El subtotal no coincide con Precio * Cantidad';
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER before_insert_order_items
BEFORE INSERT ON order_items
FOR EACH ROW
EXECUTE FUNCTION validate_order_item_subtotal();

CREATE TRIGGER before_update_order_items
BEFORE UPDATE ON order_items
FOR EACH ROW
EXECUTE FUNCTION validate_order_item_subtotal();
